spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sampledb
    username: root
    password: Ranak@89
    driver-class-name: com.mysql.jdbc.Driver